define(function(require,exports,module){
    var texts = [
        '奖就要来喽',
        '好期待',
        '嗯哼,会是我吗',
        '感觉大奖在眼前',
        '航仔给我',
        '近了，近了',
        '是我的',
        '快到碗里来',
        '谁是幸运星',
        '非我莫属',
        '给我，给我',
        '来了，来了',
        '超级大赢家',
        '求射中',
        '求大奖',
        '给一个就行',
        '我要奖品',
        '我要大奖',
        '我爱航交所',
        '一定是我的',
        'come baby',
        '100个赞',
        '今天我最帅',
        '特别的一天主持人好帅',
        '美女帅哥看过来',
        '棒棒哒',
        '求奖，求奖',
        '感觉要中',
        '一定要中',
        '不给我会哭',
        '航仔给我',
        '么么哒',
        '来一个',
        '跪求跪求',
        '航仔我爱你',
        '两周年快乐',
        '是我的就是我的',
        '喜大普奔',
        '我爱航交所',
        '航仔棒棒哒',
        'V5霸气',
        '我最幸运',
        '今天好开心'
    ];

    var names = [
        {'name':'周洁','telephone':'155****8130',loaded:0},
        {'name':'孙文军','telephone':'159****4115',loaded:1},
        {'name':'奚志明','telephone':'138****6640',loaded:1},
        {'name':'李为','telephone':'186****6677',loaded:1},
        {'name':'芦溢香','telephone':'130****7700',loaded:1},
        {'name':'王群','telephone':'186****9638',loaded:1},
        {'name':'丛轶','telephone':'133****8108',loaded:1},
        {'name':'范文浩','telephone':'138****7715',loaded:1},
        {'name':'韩笑','telephone':'135****9895',loaded:1},
        {'name':'田旻','telephone':'158****5212',loaded:0},
        {'name':'庞秋莉','telephone':'134****6069',loaded:0},
        {'name':'丁超','telephone':'186****8389',loaded:0},
        {'name':'包宗保','telephone':'185****8012',loaded:0},
        {'name':'王宁','telephone':'134****8059',loaded:0},
        {'name':'于超','telephone':'186****8081',loaded:0},
        {'name':'周丹','telephone':'186****2098',loaded:0},
        {'name':'贺文超','telephone':'130****5444',loaded:0},
        {'name':'单爱花','telephone':'136****1018',loaded:0}
    ];

	module.exports = {
        names :  names,
        texts : texts
    };
});
