define(function(require,exports,module){
    var texts = [
        '奖就要来喽',
        '好期待',
        '嗯哼,会是我吗',
        '感觉大奖在眼前',
        '航仔给我',
        '近了，近了',
        '是我的',
        '快到碗里来',
        '谁是幸运星',
        '非我莫属',
        '给我，给我',
        '来了，来了',
        '超级大赢家',
        '求射中',
        '求大奖',
        '给一个就行',
        '我要奖品',
        '我要大奖',
        '我爱航交所',
        '一定是我的',
        'come baby',
        '100个赞',
        '今天我最帅',
        '特别的一天主持人好帅',
        '美女帅哥看过来',
        '棒棒哒',
        '求奖，求奖',
        '感觉要中',
        '一定要中',
        '不给我会哭',
        '航仔给我',
        '么么哒',
        '来一个',
        '跪求跪求',
        '航仔我爱你',
        '两周年快乐',
        '是我的就是我的',
        '喜大普奔',
        '我爱航交所',
        '航仔棒棒哒',
        'V5霸气',
        '我最幸运',
        '今天好开心'
    ];

    var names = [
        {'name':'张靖','telephone':'159****9918',loaded:0},
        {'name':'郑德风','telephone':'138****2509',loaded:0},
        {'name':'曹春梅','telephone':'189****9635',loaded:0},
        {'name':'王超','telephone':'138****2793',loaded:0},
        {'name':'张婕','telephone':'136****8123',loaded:0},
        {'name':'王萍','telephone':'139****6915',loaded:0},
        {'name':'李洁','telephone':'138****5521',loaded:0},
        {'name':'金晓渊','telephone':'138****7180',loaded:0},
        {'name':'杨青悦','telephone':'159****1318',loaded:0},
        {'name':'郭志鹏','telephone':'189****9650',loaded:0},
        {'name':'龚秉华','telephone':'135****3196',loaded:0},
        {'name':'梁嵬','telephone':'136****5111',loaded:0},
        {'name':'袁悠径','telephone':'150****9889',loaded:0},
        {'name':'黄皓','telephone':'136****3092',loaded:0},
        {'name':'黄雯','telephone':'135****0699',loaded:0},
        {'name':'董诚程','telephone':'186****8385',loaded:0},
        {'name':'程柳','telephone':'139****9732',loaded:0},
        {'name':'邓楠','telephone':'156****2937',loaded:0},
        {'name':'华烨','telephone':'137****5905',loaded:0},
        {'name':'张向东','telephone':'136****3200',loaded:0},
        {'name':'钟炜','telephone':'135****6358',loaded:0},
        {'name':'朱霖','telephone':'186****7711',loaded:0},
        {'name':'张春美','telephone':'159****5597',loaded:0},
        {'name':'蔡含笑','telephone':'188****2788',loaded:0},
        {'name':'肖龙甫','telephone':'186****4846',loaded:0},
        {'name':'涂华清','telephone':'136****4687',loaded:0}
    ];

	module.exports = {
        names :  names,
        texts : texts
    };
});
